### ISSUE TITLE
[BUG] TypeError: ImgurClient is not a constructor

### ISSUE THREAD

**Issue by pkdev08** [KenEucker/imgur#214] opened 2023-01-06 08:15 UTC
import ImgurClient from 'imgur';

const client = new ImgurClient({
  clientId: process.env.CLIENT_ID,
  clientSecret: process.env.CLIENT_SECRET
});

Gives error TypeError: ImgurClient is not a constructor

On LTS node 18.12.1 using ESM

**Comment by KenEucker** [comment] 2023-01-15 07:16
@pkdev08 you need to deconstruct the ImgurClient type, as shown in the documentation:

```ts
// ESModule syntax
import { ImgurClient } from 'imgur';
```

**Comment by pkdev08** [comment] 2023-01-16 00:51
> @pkdev08 you need to deconstruct the ImgurClient type, as shown in the documentation:
> 
> ```ts
> // ESModule syntax
> import { ImgurClient } from 'imgur';
> ```

Hi, when I do that it's having export issues.

import { ImgurClient } from 'imgur';
         ^^^^^^^^^^^
SyntaxError: Named export 'ImgurClient' not found. The requested module 'imgur' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'imgur';
const { ImgurClient } = pkg;

**Comment by KenEucker** [comment] 2023-01-22 01:04
@pkdev08 can you try the following lines:

```
import imgur from 'imgur'
// @ts-expect-error
const ImgurClient = imgur.ImgurClient
```

I started running into this error in another project and I have now realized that esm imports do not work as intended, which was the primary target for this library. I will try to find a way to resolve this in the export, maybe by moving to rollup, as soon as I am able to.

**Comment by KenEucker** [comment] 2023-01-22 01:08
I just realized that this was also pointed out in a previous issue, so I am closing this ticket as it is a duplicate of the issue in #205.

**Closed by KenEucker** 2023-01-22 01:08 UTC
